/**
 * Typed wrappers over Tauri IPC — Channel B (API_DESIGN.md §7).
 *
 * The Rust shell is not built yet (Phase 4b needs the Rust toolchain), so every
 * call degrades to a documented fallback when the Tauri global is absent. That
 * is what lets the frontend be developed and tested in a plain browser today
 * and pick up the real shell later with no code change.
 *
 * The fallbacks are deliberately conservative: absence is reported as absence,
 * never as a fabricated success. `getPermissionsStatus` returning "granted" in
 * a browser would make the onboarding flow untestable.
 */

export interface RuntimeInfo {
  /** Sidecar base URL, e.g. http://127.0.0.1:52341 */
  baseUrl: string;
  /** WebSocket URL for the same sidecar. */
  wsUrl: string;
  /** 256-bit session token generated by Rust at spawn. */
  token: string;
  apiVersion: string;
}

export interface SystemMetrics {
  cpuPercent: number;
  memoryUsedBytes: number;
  memoryTotalBytes: number;
  /** Null on Apple Silicon — no unprivileged GPU API (ARCHITECTURE.md §13). */
  gpuPercent: number | null;
  batteryPercent: number | null;
  batteryCharging: boolean | null;
}

export type SidecarState = 'starting' | 'ready' | 'restarting' | 'failed';

export type PermissionName = 'accessibility' | 'screenRecording' | 'microphone';
export type PermissionState = 'granted' | 'denied' | 'notDetermined' | 'unknown';

type InvokeFn = <T>(command: string, args?: Record<string, unknown>) => Promise<T>;

interface TauriGlobal {
  core?: { invoke?: InvokeFn };
  event?: {
    listen?: <T>(event: string, handler: (e: { payload: T }) => void) => Promise<() => void>;
  };
}

function tauri(): TauriGlobal | null {
  const global = globalThis as { __TAURI__?: TauriGlobal };
  return global.__TAURI__ ?? null;
}

export function isTauriAvailable(): boolean {
  return typeof tauri()?.core?.invoke === 'function';
}

async function invoke<T>(command: string, args?: Record<string, unknown>): Promise<T> {
  const fn = tauri()?.core?.invoke;
  if (fn === undefined) {
    throw new ShellUnavailableError(command);
  }
  return fn<T>(command, args);
}

export class ShellUnavailableError extends Error {
  constructor(readonly command: string) {
    super(`Tauri shell unavailable — cannot invoke "${command}" (Phase 4b)`);
    this.name = 'ShellUnavailableError';
  }
}

// -- runtime handshake ------------------------------------------------------

/**
 * Fetch the sidecar port and session token.
 *
 * Outside the shell, falls back to Vite env vars so `npm run dev` can point at a
 * manually started sidecar. There is no default token: a hardcoded one would be
 * a credential in the source tree, which DEC-017 forbids regardless of how
 * development-only it claims to be.
 */
export async function getRuntimeInfo(): Promise<RuntimeInfo> {
  if (isTauriAvailable()) {
    return invoke<RuntimeInfo>('get_runtime_info');
  }

  const env = import.meta.env;
  const baseUrl = env['VITE_MITTA_BASE_URL'];
  const token = env['VITE_MITTA_TOKEN'];
  if (typeof baseUrl !== 'string' || typeof token !== 'string') {
    throw new ShellUnavailableError('get_runtime_info');
  }
  return {
    baseUrl,
    wsUrl: `${baseUrl.replace(/^http/, 'ws')}/v1/ws`,
    token,
    apiVersion: '1',
  };
}

// -- secrets (DEC-017) ------------------------------------------------------

/**
 * Write an API key to the macOS Keychain.
 *
 * This is the ONLY path a key ever takes. It goes from the settings input
 * directly to Rust to the Keychain — never through the sidecar's HTTP API,
 * because an endpoint that accepts a key is an endpoint that logs a key the
 * first time someone enables request logging.
 */
export function storeApiKey(provider: string, key: string): Promise<void> {
  return invoke<void>('store_api_key', { provider, key });
}

/** Presence check only. A key value is never read back into the webview. */
export function hasApiKey(provider: string): Promise<boolean> {
  return invoke<boolean>('has_api_key', { provider });
}

export function deleteApiKey(provider: string): Promise<void> {
  return invoke<void>('delete_api_key', { provider });
}

// -- window control ---------------------------------------------------------

export function togglePalette(): Promise<void> {
  return invoke<void>('toggle_palette');
}

export function hideWindow(): Promise<void> {
  return invoke<void>('window_hide');
}

export function openPath(path: string): Promise<void> {
  return invoke<void>('open_path', { path });
}

export function revealInFinder(path: string): Promise<void> {
  return invoke<void>('reveal_in_finder', { path });
}

// -- permissions ------------------------------------------------------------

export async function getPermissionsStatus(): Promise<Record<PermissionName, PermissionState>> {
  if (!isTauriAvailable()) {
    return { accessibility: 'unknown', screenRecording: 'unknown', microphone: 'unknown' };
  }
  return invoke<Record<PermissionName, PermissionState>>('get_permissions_status');
}

// -- events -----------------------------------------------------------------

/**
 * Subscribe to a Rust-emitted event. Returns an unsubscribe function.
 *
 * Metrics arrive here rather than over the WebSocket: sampling happens in Rust
 * at 1 Hz (DEC-003), and routing them through Python would add a hop, a
 * serialisation and a poll loop to the one thing that runs every second for the
 * entire session.
 */
export async function listen<T>(event: string, handler: (payload: T) => void): Promise<() => void> {
  const listener = tauri()?.event?.listen;
  if (listener === undefined) {
    return () => {};
  }
  return listener<T>(event, (e) => handler(e.payload));
}

export function onMetrics(handler: (metrics: SystemMetrics) => void): Promise<() => void> {
  return listen<SystemMetrics>('metrics:update', handler);
}

export function onSidecarState(handler: (state: SidecarState) => void): Promise<() => void> {
  return listen<SidecarState>('sidecar:state', handler);
}
