/**
 * Typed wrappers over Tauri IPC — Channel B (API_DESIGN.md §7).
 *
 * Every call degrades to a documented fallback when the shell is absent, which
 * is what lets the frontend run in a plain browser (`make dev`) and in the
 * desktop app (`make app`) from the same source.
 *
 * The fallbacks are deliberately conservative: absence is reported as absence,
 * never as a fabricated success. `getPermissionsStatus` returning "granted" in
 * a browser would make the onboarding flow untestable.
 */

export interface RuntimeInfo {
  /** Sidecar base URL, e.g. http://127.0.0.1:52341 */
  baseUrl: string;
  /** WebSocket URL for the same sidecar. */
  wsUrl: string;
  /** 256-bit session token generated by Rust at spawn. */
  token: string;
  apiVersion: string;
}

export interface SystemMetrics {
  cpuPercent: number;
  memoryUsedBytes: number;
  memoryTotalBytes: number;
  /** Null on Apple Silicon — no unprivileged GPU API (ARCHITECTURE.md §13). */
  gpuPercent: number | null;
  batteryPercent: number | null;
  batteryCharging: boolean | null;
}

export type SidecarState = 'starting' | 'ready' | 'restarting' | 'failed';

export type PermissionName = 'accessibility' | 'screenRecording' | 'microphone';
export type PermissionState = 'granted' | 'denied' | 'notDetermined' | 'unknown';

/**
 * Detecting the shell.
 *
 * The first version checked `window.__TAURI__`, which Tauri v2 injects **only**
 * when `withGlobalTauri` is set. It was not, so every call fell through to its
 * browser fallback and the app reported "Disconnected" while the Rust side ran
 * perfectly — nothing logged an error, because a fallback firing is a normal
 * state that the browser path depends on.
 *
 * `__TAURI_INTERNALS__` is present whenever the webview is Tauri's, regardless
 * of that flag, so detection no longer depends on a config option that can be
 * changed without anything failing.
 */
export function isTauriAvailable(): boolean {
  return '__TAURI_INTERNALS__' in globalThis;
}

async function invoke<T>(command: string, args?: Record<string, unknown>): Promise<T> {
  if (!isTauriAvailable()) {
    throw new ShellUnavailableError(command);
  }
  // Imported lazily so the browser build never pulls the package in, and so a
  // module-load failure surfaces as a failed call rather than a blank window.
  const { invoke: tauriInvoke } = await import('@tauri-apps/api/core');
  return tauriInvoke<T>(command, args);
}

export class ShellUnavailableError extends Error {
  constructor(readonly command: string) {
    super(`Tauri shell unavailable — cannot invoke "${command}" (Phase 4b)`);
    this.name = 'ShellUnavailableError';
  }
}

// -- runtime handshake ------------------------------------------------------

/**
 * Fetch the sidecar port and session token.
 *
 * Outside the shell, falls back to what `scripts/dev.sh` put in the
 * environment. There is no default token: a hardcoded one would be a credential
 * in the source tree, which DEC-017 forbids regardless of how
 * development-only it claims to be.
 *
 * The dev `baseUrl` is the **page's own origin**, not the sidecar's. Vite
 * proxies `/v1` and `/health` through to it, so requests are same-origin and no
 * CORS is needed — the sidecar ships none on purpose. Everything above this
 * function is therefore identical in dev and in the shell.
 */
export async function getRuntimeInfo(): Promise<RuntimeInfo> {
  if (isTauriAvailable()) {
    return invoke<RuntimeInfo>('get_runtime_info');
  }

  const env = import.meta.env;
  const token = env['VITE_MITTA_TOKEN'];
  if (typeof token !== 'string' || typeof env['VITE_MITTA_BASE_URL'] !== 'string') {
    throw new ShellUnavailableError('get_runtime_info');
  }

  const origin = globalThis.location.origin;
  return {
    baseUrl: origin,
    wsUrl: `${origin.replace(/^http/, 'ws')}/v1/ws`,
    token,
    apiVersion: '1',
  };
}

// -- secrets (DEC-017) ------------------------------------------------------

/**
 * Write an API key to the macOS Keychain.
 *
 * This is the ONLY path a key ever takes. It goes from the settings input
 * directly to Rust to the Keychain — never through the sidecar's HTTP API,
 * because an endpoint that accepts a key is an endpoint that logs a key the
 * first time someone enables request logging.
 */
export function storeApiKey(provider: string, key: string): Promise<void> {
  return invoke<void>('store_api_key', { provider, key });
}

/** Presence check only. A key value is never read back into the webview. */
export function hasApiKey(provider: string): Promise<boolean> {
  return invoke<boolean>('has_api_key', { provider });
}

export function deleteApiKey(provider: string): Promise<void> {
  return invoke<void>('delete_api_key', { provider });
}

// -- window control ---------------------------------------------------------

export function togglePalette(): Promise<void> {
  return invoke<void>('toggle_palette');
}

export function hideWindow(): Promise<void> {
  return invoke<void>('window_hide');
}

export function openPath(path: string): Promise<void> {
  return invoke<void>('open_path', { path });
}

export function revealInFinder(path: string): Promise<void> {
  return invoke<void>('reveal_in_finder', { path });
}

// -- permissions ------------------------------------------------------------

export async function getPermissionsStatus(): Promise<Record<PermissionName, PermissionState>> {
  if (!isTauriAvailable()) {
    return { accessibility: 'unknown', screenRecording: 'unknown', microphone: 'unknown' };
  }
  return invoke<Record<PermissionName, PermissionState>>('get_permissions_status');
}

// -- events -----------------------------------------------------------------

/**
 * Subscribe to a Rust-emitted event. Returns an unsubscribe function.
 *
 * Metrics arrive here rather than over the WebSocket: sampling happens in Rust
 * at 1 Hz (DEC-003), and routing them through Python would add a hop, a
 * serialisation and a poll loop to the one thing that runs every second for the
 * entire session.
 */
export async function listen<T>(event: string, handler: (payload: T) => void): Promise<() => void> {
  if (!isTauriAvailable()) {
    // A browser has no Rust side to emit anything. A no-op unsubscribe keeps
    // every caller's teardown path identical.
    return () => {};
  }
  const { listen: tauriListen } = await import('@tauri-apps/api/event');
  return tauriListen<T>(event, (e) => handler(e.payload));
}

export function onMetrics(handler: (metrics: SystemMetrics) => void): Promise<() => void> {
  return listen<SystemMetrics>('metrics:update', handler);
}

export function onSidecarState(handler: (state: SidecarState) => void): Promise<() => void> {
  return listen<SidecarState>('sidecar:state', handler);
}

// -- voice (R7, DEC-105) ----------------------------------------------------

export type ListenState = 'idle' | 'listening' | 'failed';

export interface VoiceUpdate {
  state: ListenState;
  transcript: string;
  isFinal: boolean;
  /** 0..1, sampled from the real audio tap. Never synthesised — a waveform that
   *  moves with the microphone closed is a lie about whether you are recorded. */
  level: number;
  speaking: boolean;
  continuous: boolean;
  error: string | null;
  /** The wake word was heard in continuous mode. */
  triggered: boolean;
}

/** Ask for microphone and speech access. The prompt is modal; poll
 *  `getPermissionsStatus` for the answer rather than awaiting this. */
export function requestVoicePermission(): Promise<void> {
  return invoke<void>('voice_request_permission');
}

/** Open the microphone. `continuous` enables wake-word mode (DEC-105). */
export function startListening(continuous = false): Promise<void> {
  return invoke<void>('voice_start', { continuous });
}

export function stopListening(): Promise<void> {
  return invoke<void>('voice_stop');
}

/**
 * Tune the speech gate to this room and this voice. Returns the threshold set.
 *
 * `observed` is the ambient level measured from the update stream during a quiet
 * moment. This is the part of "train MITTA to my voice" that Apple's APIs allow:
 * not a voiceprint — no public framework offers speaker adaptation — but the
 * threshold that decides whether the wake word is heard at all, fitted to how
 * loud you are and how noisy the room is.
 */
export function calibrateVoice(observed: number): Promise<number> {
  return invoke<number>('voice_calibrate', { observed });
}

export function speak(text: string, rate = 0): Promise<void> {
  return invoke<void>('voice_speak', { text, rate });
}

export function stopSpeaking(): Promise<void> {
  return invoke<void>('voice_stop_speaking');
}

/**
 * Push-to-talk from the global shortcut, which fires even when MITTA is not focused.
 *
 * `true` on press, `false` on release. The webview decides what the utterance
 * means — filling the composer and sending — so the shell only reports the
 * gesture; putting that logic on both sides would give one chord two behaviours.
 */
export function onPushToTalk(handler: (down: boolean) => void): Promise<() => void> {
  return listen<boolean>('voice:push_to_talk', handler);
}

export function onVoiceUpdate(handler: (update: VoiceUpdate) => void): Promise<() => void> {
  return listen<VoiceUpdate>('voice:update', handler);
}

/** Whether the shell can do speech at all. False in a browser (`make dev`),
 *  where there is no Rust side and therefore no Speech framework. */
export function isVoiceAvailable(): boolean {
  return isTauriAvailable();
}

export interface VoiceChoice {
  id: string;
  name: string;
  language: string;
  quality: 'compact' | 'enhanced' | 'premium';
}

export interface VoiceInfo {
  name: string;
  quality: 'compact' | 'enhanced' | 'premium';
  /** Only compact voices are installed. The good ones are a free download that
   *  macOS does not mention anywhere the user would look. */
  canImprove: boolean;
  available: VoiceChoice[];
}

export function getVoiceInfo(): Promise<VoiceInfo> {
  return invoke<VoiceInfo>('voice_info');
}

export function setVoice(identifier: string | null): Promise<void> {
  return invoke<void>('voice_set_voice', { identifier });
}

/** Open the Settings pane where macOS keeps its downloadable voices. */
export function openVoiceSettings(): Promise<void> {
  return invoke<void>('voice_open_settings');
}
