#!/usr/bin/env bash
#
# Run MITTA in development: the Python sidecar plus the Vite dev server, wired
# together, on a scratch storage root.
#
# This exists because the Tauri shell is Phase 4b. In the real application Rust
# spawns the sidecar, generates the session token and hands both to the webview
# over IPC. Until then something has to play that role, and it should play it
# honestly: a token is **generated per run**, never hardcoded. A development
# token committed to the tree is a credential in the source tree (DEC-017), and
# "it's only for dev" is exactly what is said about every credential that later
# turns out to be in production.
#
#   ./scripts/dev.sh                 # scratch storage root under .dev/
#   ./scripts/dev.sh --real-storage  # your actual MITTA data
#
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PY="${ROOT}/.venv/bin/python"
UI="${ROOT}/apps/desktop"
ENV_FILE="${UI}/.env.local"

STORAGE_ROOT="${ROOT}/.dev/storage"
for arg in "$@"; do
  case "$arg" in
    --real-storage) STORAGE_ROOT="" ;;
    *) echo "unknown option: $arg" >&2; exit 2 ;;
  esac
done

if [[ ! -x "$PY" ]]; then
  echo "No virtualenv at ${PY}. Run 'make install' first." >&2
  exit 1
fi
if [[ ! -d "${UI}/node_modules" ]]; then
  echo "Frontend dependencies missing. Run 'make install-ui' first." >&2
  exit 1
fi

TOKEN="$("$PY" -c 'import secrets; print(secrets.token_urlsafe(32))')"
LOG_DIR="${ROOT}/.dev"
mkdir -p "$LOG_DIR"
SIDECAR_LOG="${LOG_DIR}/sidecar.log"
: > "$SIDECAR_LOG"

cleanup() {
  local code=$?
  [[ -n "${SIDECAR_PID:-}" ]] && kill "$SIDECAR_PID" 2>/dev/null || true
  # The token dies with the run. Leaving it behind would mean a stale
  # credential sitting in the working tree until the next dev session.
  rm -f "$ENV_FILE"
  exit $code
}
trap cleanup EXIT INT TERM

echo "▸ starting sidecar…"
if [[ -n "$STORAGE_ROOT" ]]; then
  mkdir -p "$STORAGE_ROOT"
  echo "  storage  ${STORAGE_ROOT}  (scratch — pass --real-storage to use your own)"
  MITTA_STORAGE_ROOT="$STORAGE_ROOT" MITTA_SESSION_TOKEN="$TOKEN" MITTA_DEV_MODE=1 \
    "$PY" -m mitta >> "$SIDECAR_LOG" 2>&1 &
else
  echo "  storage  your real MITTA data"
  MITTA_SESSION_TOKEN="$TOKEN" MITTA_DEV_MODE=1 "$PY" -m mitta >> "$SIDECAR_LOG" 2>&1 &
fi
SIDECAR_PID=$!

PORT=""
for _ in $(seq 1 100); do
  if ! kill -0 "$SIDECAR_PID" 2>/dev/null; then
    echo "✗ sidecar exited during startup:" >&2
    tail -20 "$SIDECAR_LOG" >&2
    exit 1
  fi
  PORT="$(grep -m1 '^MITTA_READY' "$SIDECAR_LOG" 2>/dev/null | awk '{print $2}' || true)"
  [[ -n "$PORT" ]] && break
  sleep 0.1
done

if [[ -z "$PORT" ]]; then
  echo "✗ sidecar never announced a port. Last output:" >&2
  tail -20 "$SIDECAR_LOG" >&2
  exit 1
fi

# Vite only exposes VITE_-prefixed vars to the client, which is the boundary
# that keeps unrelated environment out of the bundle.
cat > "$ENV_FILE" <<ENVEOF
# Generated by scripts/dev.sh. Deleted when it exits. Never commit this.
VITE_MITTA_BASE_URL=http://127.0.0.1:${PORT}
VITE_MITTA_TOKEN=${TOKEN}
ENVEOF

echo "  sidecar  http://127.0.0.1:${PORT}  (pid ${SIDECAR_PID}, log .dev/sidecar.log)"
if grep -q 'embedding_model_absent' "$SIDECAR_LOG"; then
  echo "  model    not downloaded — semantic recall degraded ('make download-model')"
fi
echo "▸ starting vite…"
echo

cd "$UI" && npm run dev
